export const CITIES = [
    {
        id: 'raleigh-nc',
        name: "Raleigh, NC",
        file: "NC/raleigh.geojson",
        lat: 35.7796,
        lng: -78.6382,
        src: "https://data-ral.opendata.arcgis.com/datasets/a8cd851199cc46029b6b73151711ab75_0/explore?location=35.828283%2C-78.644874%2C10.28",
        added_date: "2026-01-03",
        source_date: "2025-10-09"
    },
    {
        id: 'charlotte-nc',
        name: "Charlotte, NC",
        file: "NC/charlotte.geojson",
        lat: 35.2271,
        lng: -80.8431,
        src: "https://data.charlottenc.gov/datasets/charlotte::cmpd-police-divisions-1/about",
        added_date: "2026-01-03",
        source_date: "2024-12-04"
    },
    {
        id: 'los-angeles-ca',
        name: "Los Angeles, CA",
        file: "CA/los_angeles.geojson",
        lat: 34.0522,
        lng: -118.2437,
        src: "https://geohub.lacity.org/datasets/lapd-divisions",
        added_date: "2026-01-03",
        source_date: "2023-04-28"
    },
    {
        id: 'sacramento-ca',
        name: "Sacramento, CA",
        file: "CA/sacramento.geojson",
        lat: 38.5816,
        lng: -121.4944,
        src: "https://data.saccounty.gov/datasets/sacramentocounty::sheriff-districts-1/explore?location=38.339142%2C-121.359043%2C9.24",
        added_date: "2026-01-03",
        source_date: "2021-07-15"
    },
    {
        id: 'chicago-il',
        name: "Chicago, IL",
        file: "IL/chicago.geojson",
        lat: 41.8781,
        lng: -87.6298,
        src: "https://data.cityofchicago.org/Public-Safety/Boundaries-Police-Districts-current-/fthy-xz3r",
        added_date: "2026-01-03",
        source_date: "2024-12-02"
    },
    {
        id: 'atlanta-ga',
        name: "Atlanta, GA",
        file: "GA/atlanta.geojson",
        lat: 33.7501,
        lng: -84.3885,
        src: "https://opendata.atlantaregional.com/datasets/coaplangis::atlanta-police-department-zones-2019/about",
        added_date: "2026-01-03",
        source_date: "2023-05-23"
    },
    {
        id: 'philadelphia-pa',
        name: "Philadelphia, PA",
        file: "PA/philadelphia.geojson",
        lat: 40.0094,
        lng: -75.1333,
        src: "https://opendataphilly.org/datasets/police-districts/",
        added_date: "2026-01-03",
        source_date: "2026-01-03" // update this
    },
    {
        id: 'arlington-tx',
        name: "Arlington, TX",
        file: "TX/arlington.geojson",
        lat: 32.7007,
        lng: -97.1247,
        src: "https://opendata.arlingtontx.gov/datasets/arlington-police-districts/explore",
        added_date: "2026-01-03",
        source_date: "2023-05-25"
    },
    {
        id: 'denver-co',
        name: "Denver, CO",
        file: "CO/denver.geojson",
        lat: 39.7619,
        lng: -104.8811,
        src: "https://opendata-geospatialdenver.hub.arcgis.com/datasets/202b2bb479034e839a7587caa84be3f6_367/explore?location=39.727844%2C-104.921921%2C10.56",
        added_date: "2026-01-03",
        source_date: "2026-01-03" // update this
    },
    {
        id: 'austin-tx',
        name: "Austin, TX",
        file: "TX/austin.geojson",
        lat: 30.3039,
        lng: -97.7544,
        src: "https://data.austintexas.gov/dataset/Austin-Police-Department-Districts/9jeg-fsk5",
        added_date: "2026-01-03",
        source_date: "2026-01-03", // update this
    },
    {
        id: 'new_york_city-ny',
        name: 'New York City, NY',
        file: "NY/new_york_city.geojson",
        lat: 40.6635,
        lng: -73.9387,
        src: "https://www.nyc.gov/content/planning/pages/resources/datasets/police-precincts",
        added_date: "2026-01-07",
        source_date: "2025-11-01"
    },
    {
        id: "detroit-mi",
        name: "Detroit, MI",
        file: "MI/detroit.geojson",
        lat: 42.3528,
        lng: -83.099,
        src: "https://data.detroitmi.gov/datasets/dpd-precincts/explore",
        added_date: "2026-01-09",
        source_date: "2020-11-06"
    },
    {
        id: "baltimore-md",
        name: "Baltimore, MD",
        file: "MD/baltimore.geojson",
        lat: 39.2846,
        lng: -76.6205,
        src: "https://hub.arcgis.com/api/v3/datasets/3d893a4354944a629b3d16ee69cb02f1_0/downloads/data?format=geojson&spatialRefId=4326&where=1%3D1",
        added_date: "2026-01-12",
        source_date: "2025-07-17"
    },
    {
        id: "miami-fl",
        name: "Miami, FL",
        file: "FL/miami.geojson",
        lat: 25.7824,
        lng: -80.2278,
        src: "https://datahub-miamigis.opendata.arcgis.com/datasets/18ea60e4964943a4981b60d800fe28e0_0/explore?location=25.782469%2C-80.227576%2C11",
        added_date: "2026-02-10",
        source_date: "2024-10-22"
    },
    {

        id: "portland-or",
        name: "Portland, OR",
        file: "OR/portland.geojson",
        lat: 45.5449,
        lng: -122.646,
        src: "https://gis-pdx.opendata.arcgis.com/datasets/PDX::police-districts-ppb/about",
        district_field: "DISTRICT",
        added_date: "2026-02-12",
        source_date: "2024-09-12"

    }
];

export const STATE_NAMES = {
    "AL": "Alabama",
    "AK": "Alaska",
    "AZ": "Arizona",
    "AR": "Arkansas",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DE": "Delaware",
    "DC": "District of Columbia",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "IA": "Iowa",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "ME": "Maine",
    "MD": "Maryland",
    "MA": "Massachusetts",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MS": "Mississippi",
    "MO": "Missouri",
    "MT": "Montana",
    "NE": "Nebraska",
    "NV": "Nevada",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NY": "New York",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VT": "Vermont",
    "VA": "Virginia",
    "WA": "Washington",
    "WV": "West Virginia",
    "WI": "Wisconsin",
    "WY": "Wyoming"
};
